### ISSUE TITLE
Use of path.join to concatenate URL makes it not work in Windows

### ISSUE THREAD

**Issue by RangelReale** [jacksmith15/json-ref-dict#19]
`
statham --input https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/prometheus.json

<...>

json_ref_dict.exceptions.DocumentParseError: Failed to load base document of https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json\prometheus.json#/
`

This is because of "uri.py:root()" using "path.join", which uses the platform separator, and breaks in Windows.

**Comment by jacksmith15** [comment]
Thanks for raising, just linking your PR: #20

**Comment by jacksmith15** [comment]
Fix merged, to be released in 0.6.1
